name: generate-website

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: [roleever-pi]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn generate --fail-on-error
