name: generate-and-deploy-website

# Controls when the action will run. 
on:
  push:
    branches:
      - prod
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        
      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn install

      - name: 🔨 Generate static website
        run: yarn generate --fail-on-error
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: ./dist/
            server-dir: www.roleever.com/
            exclude: .git*
              - images/**
              - favicon/**
              - media/**
