# This is a basic workflow to help you get started with Actions

name: generate-website

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        
      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn install

      - name: 🔨 Generate static website
        run: yarn generate --fail-on-error
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
            server: ftp.roleever.com
            username: 11390053@aruba.it
            password: ${{ secrets.ftp_password }}
            local-dir: ./dist/
            server-dir: www.roleever.com/test/
